import { mockCatCardProps } from "@/components/card/CatCard.mocks";
import { Layout, SideBar } from "@/components/layouts";
import Head from "next/head";
import CatCard from "../src/components/card/CatCard";
import styles from "../styles/Home.module.css";
import { NextPageWithLayout } from "./page";

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CatCard {...mockCatCardProps.base} />
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
};

export default Home;

Home.getLayout = (page) => {
  return (
    <Layout>
      <SideBar />
      {page}
    </Layout>
  );
};
